<?php

use NetworkRailBusinessSystems\DirectoryLink\Models\DirectoryUser;
use NetworkRailBusinessSystems\DirectoryLink\Models\DirectoryGroup;

return [
    /* Which Models to use for directory operations */
    'models' => [
        'group' => [
            'directory' => DirectoryGroup::class,
            'local' => 'App\Models\Group',
        ],
        'user' => [
            'directory' => DirectoryUser::class,
            'local' => 'App\Models\User',
        ],
    ],

    /* Which attributes to sync in directory => system format */
    'sync' => [
        'group' => [
            'on' => 'id',
            'attributes' => [
                'description' => 'description',
                'displayName' => 'name',
                'id' => 'azure_id',
                'mail' => 'email',
                'members' => 'members',
                'membersCount' => 'count',
            ],
        ],
        'user' => [
            'on' => 'id',
            'attributes' => [
                'department' => 'business_area',
                'displayName' => 'name',
                'employeeId' => 'employee_number',
                'givenName' => 'first_name',
                'id' => 'azure_id',
                'jobTitle' => 'title',
                'mail' => 'email',
                'officeLocation' => 'location',
                'phone' => 'phone',
                'surname' => 'last_name',
            ],
        ],
    ],

    /* API connection credentials */
    'api' => [
        'endpoint' => env('DIRECTORY_ENDPOINT'),
        'proxy' => env('DIRECTORY_PROXY'),
        'token' => env('DIRECTORY_TOKEN'),
    ],

    /* Emulator options - remove after publishing to keep defaults */
    'emulator' => [
        'enabled' => env('DIRECTORY_EMULATOR', false),
        'groups' => [
            [
                'description' => 'A group of fellows on a quest to destroy the one ring',
                'displayName' => 'The Fellowship of the Ring',
                'id' => 'grp123ab-6789-01de-f2g3-45678hijk9lm',
                'mail' => 'fellowship@middle-earth.com',
                'members' => [
                    'gandalf.stormcrow@networkrail.co.uk',
                    'frodo.baggins@networkrail.co.uk',
                    'samwise.gamgee@networkrail.co.uk',
                    'aragorn.elessar@networkrail.co.uk',
                    'legolas.thranduil@networkrail.co.uk',
                    'gimli.gloin@networkrail.co.uk',
                    'boromir.denethor@networkrail.co.uk',
                    'merry.brandybuck@networkrail.co.uk',
                    'peregrin.took@networkrail.co.uk',
                ],
                'membersCount' => 10,
            ],
        ],
        'users' => [
            [
                'businessPhones' => '01234567890',
                'department' => 'Wizardry',
                'displayName' => 'Gandalf Stormcrow',
                'employeeId' => '123456',
                'givenName' => 'Gandalf',
                'id' => '123ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'Wizard',
                'mail' => 'gandalf.stormcrow@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'Minas Tirith',
                'phone' => '01234567890',
                'surname' => 'Stormcrow',
                'userPrincipalName' => 'gandalf@networkrail.co.uk',
            ],
            [
                'businessPhones' => '01234567890',
                'department' => 'The Green Dragon',
                'displayName' => 'Frodo Baggins',
                'employeeId' => '123456',
                'givenName' => 'Frodo',
                'id' => '234ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'Ring Bearer',
                'mail' => 'frodo.baggins@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'Bag End',
                'phone' => '01234567890',
                'surname' => 'Baggins',
                'userPrincipalName' => 'frodo@networkrail.co.uk',
            ],
            [
                'businessPhones' => '01234567890',
                'department' => 'The Green Dragon',
                'displayName' => 'Samwise Gamgee',
                'employeeId' => '123456',
                'givenName' => 'Samwise',
                'id' => '345ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'Gardener',
                'mail' => 'samwise.gamgee@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'The Shire',
                'phone' => '01234567890',
                'surname' => 'Gamgee',
                'userPrincipalName' => 'samwise@networkrail.co.uk',

            ],
            [
                'businessPhones' => '01234567890',
                'department' => 'Hunting',
                'displayName' => 'Aragorn Elessar',
                'employeeId' => '123456',
                'givenName' => 'Aragorn',
                'id' => '456ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'King',
                'mail' => 'aragorn.elessar@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'Minas Tirith',
                'phone' => '01234567890',
                'surname' => 'Elessar',
                'userPrincipalName' => 'aragorn@networkrail.co.uk',
            ],
            [
                'businessPhones' => '01234567890',
                'department' => 'Hunting',
                'displayName' => 'Legolas Thranduil',
                'employeeId' => '123456',
                'givenName' => 'Legolas',
                'id' => '567ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'Prince',
                'mail' => 'legolas.thranduil@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'Mirkwood',
                'phone' => '01234567890',
                'surname' => 'Thranduil',
                'userPrincipalName' => 'legolas@networkrail.co.uk',
            ],
            [
                'businessPhones' => '01234567890',
                'department' => 'Hunting',
                'displayName' => 'Gimli Gloin',
                'employeeId' => '123456',
                'givenName' => 'Gimli',
                'id' => '678ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'Lord',
                'mail' => 'gimli.gloin@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'Moria',
                'phone' => '01234567890',
                'surname' => 'Gloin',
                'userPrincipalName' => 'gimli@networkrail.co.uk',
            ],
            [
                'businessPhones' => '01234567890',
                'department' => 'Stewards',
                'displayName' => 'Boromir Denethor',
                'employeeId' => '123456',
                'givenName' => 'Boromir',
                'id' => '789ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'High Warden',
                'mail' => 'boromir.denethor@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'Anduin',
                'phone' => '01234567890',
                'surname' => 'Denethor',
                'userPrincipalName' => 'boromir@networkrail.co.uk',
            ],
            [
                'businessPhones' => '01234567890',
                'department' => 'The Green Dragon',
                'displayName' => 'Merry Brandybuck',
                'employeeId' => '123456',
                'givenName' => 'Merry',
                'id' => '890ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'Troublemaker',
                'mail' => 'Merry.Brandybuck@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'Green Dragon Inn',
                'phone' => '01234567890',
                'surname' => 'Brandybuck',
                'userPrincipalName' => 'merry@networkrail.co.uk',
            ],
            [
                'businessPhones' => '01234567890',
                'department' => 'The Green Dragon',
                'displayName' => 'Peregrin Took',
                'employeeId' => null,
                'givenName' => 'Peregrin',
                'id' => '901ab4c5-6789-01de-f2g3-45678hijk9lm',
                'jobTitle' => 'Fool',
                'mail' => 'peregrin.took@networkrail.co.uk',
                'mobilePhone' => '01234567890',
                'officeLocation' => 'Green Dragon Inn',
                'phone' => '01234567890',
                'surname' => 'Took',
                'userPrincipalName' => 'peregrin@networkrail.co.uk',
            ],
        ],
    ],
];
